services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_DB: dbtest
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbuserpassword
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres18:/var/lib/postgresql/data/18/docker