version: '3'

services: 
  web:
    image: nginx:1.14.0
    ports:
      - 80:80
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
    networks: 
      - lemp_network

  php:
    image: php_fpm
    volumes:
      - ./public_html:/public_html
    expose:
      - 9000
    networks:
      - lemp_network
  
  mysql:
      image: mysql:5.7.30
      ports:
        - 3306:3306
      volumes:
        - ./data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=f6w9Lo9o
        - MYSQL_DATABASE=agua
        - MYSQL_USER=casf
        - MYSQL_PASSWORD=f6w9Lo9o  
      command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"    
      networks:
        - lemp_network

networks:
     lemp_network:
